### ISSUE TITLE
Build a hackintosh

### ISSUE THREAD

**Issue by ziulev** [shiruken/hackintosh#11]
Hi @shiruken 👋.
Thank you so much for your work and for sharing. 🚀
* Does your build work for 100%?
* I am going to build a hackintosh. Would you recommend me to buy 1/1 configuration like yours?
Or maybe something different?

**Comment by shiruken** [comment]
I haven't personally encountered any issues so far. However my hardware is over a year old at this point so you should be able to upgrade some components.

I would recommend swapping the memory modules since [others have reported X.M.P. compatibility issues](https://www.reddit.com/r/buildapc/comments/bqsr0s/z390_aorus_pro_wifi_ram_compatibility/) with the Gigabyte Z390 AORUS PRO WIFI motherboard. The official Gigabyte "qualified vendors list" for the motherboard is available [here](https://download.gigabyte.com/FileList/Memory/mb_memory_z390-aorus-pro-wifi_191113.pdf).
