### ISSUE TITLE
Bluetooth instability in macOS Monterey

### ISSUE THREAD

**Issue by shiruken** [shiruken/hackintosh#13]
There are currently issues with Bluetooth in macOS Monterey with this configuration. Bluetooth cannot be turned off from Control Center and the System Preferences pane cannot be loaded. ~~It also appears that Bluetooth is significantly slowing down system launch (now takes several minutes).~~

The OpenIntelWireless team [indicates](https://openintelwireless.github.io/IntelBluetoothFirmware/FAQ.html#what-additional-steps-should-i-do-to-make-bluetooth-work-on-macos-monterey) that additional steps must be taken to make Bluetooth work in macOS Monterey when using [IntelBluetoothFirmware](https://github.com/OpenIntelWireless/IntelBluetoothFirmware). This includes adding `BlueToolFixup.kext` from [acidanthera/BrcmPatchRAM](https://github.com/acidanthera/BrcmPatchRAM) to the configuration (see 9ef0af4a6d515441069a68107db29ff87edc4b2c).

However, there are [still outstanding issues with BlueToolFixup in macOS Monterey](https://github.com/acidanthera/bugtracker/issues/1821) that appear to be related to the problems I have encountered. ~~Since the slow boot time is a minor inconvenience and I rarely use Bluetooth peripherals on my system, I will not be removing it from my configuration at this time in hopes of a quick fix.~~ However, if you want to avoid the instability caused by this issue, simply disable IntelBluetoothFirmware by removing it from your OC config.

![System Preferences Bluetooth Error](https://user-images.githubusercontent.com/867617/140099648-c61dfe14-d625-41dc-9918-6c0dd6fff7ab.png)

**Comment by hanselsin** [comment]
I suppose the slow boot time to several minutes might not be due to Bluetooth but rather the Samsung 970 EVO Plus SSD incompatibility with Monterey SSD TRIM handling. Google it on the net and you can find quite a lot of discussions these days. Right now I am switching the OpenCore SetApfsTrimTimeout=4299999999 (the actual value is the 32-bit unsigned MAX, just check it out yourself) to length macOS kernel to wait for Samsung SSD TRIM command returns.

**Comment by shiruken** [comment]
Hmm interesting... Does increasing the timeout to max allow the trim operation to complete on Samsung SSDs and result in faster subsequent boots? Or is this just a fix to allow the trim operation to run properly without resolving the boot time issues?

**Comment by hanselsin** [comment]
Check this out from OpenCore developers:

https://github.com/dortania/bugtracker/issues/192

Since the TRIM protocol between macOS Monterey and Samsung is now broken, setting the value to 32-bit MAX simply forces macOS kernel to wait -nearly- indefinitely long for Samsung SSD to complete each TRIM command, since we scared it will kill the SSD due to too many TRIM commands issued concurrently. I also wonder if the 4294967295 is really needed or not (say maybe just 10000000 even in ms is more than enough), so far no one has a concrete answer yet.

**Comment by shiruken** [comment]
Seems like setting it to any very high number would be suitable. 4294967295 is just convenient because it is the max allowable number (OpenCore appears to use 32-bit unsigned int for `plist int` fields).

**Comment by shiruken** [comment]
Removed boot slowdowns from this issue and created #15
