### ISSUE TITLE
An Error Occurred Preparing the Software Update

### ISSUE THREAD

**Issue by xukeek** [shiruken/hackintosh#14]
Hello I got at error ""An Error Occurred Preparing the Software Update" when install

**Comment by shiruken** [comment]
Sorry, I'm not really able to help resolve problems like this since it's a macOS error and nothing specific to building a Hackintosh. It looks like a fairly common error based on [Google search results](https://www.google.com/search?q=an+error+occurred+preparing+the+software+update+hackintosh+site:www.reddit.com) for the phrase in the r/hackintosh subreddit.

**Comment by xukeek** [comment]
Thanks, which folder should i use to install  'EFI_install' or 'EFI' in repo?

**Comment by shiruken** [comment]
`EFI_install` was the EFI directory on my USB flash drive used during my initial installation of macOS. `EFI` is my current EFI directory on my boot drive that I keep up-to-date.

You really should be following [Dortania's OpenCore Install Guide](https://dortania.github.io/OpenCore-Install-Guide/) rather than relying upon existing configurations, especially if you have any differences in hardware.
