### ISSUE TITLE
Help wanted!

### ISSUE THREAD

**Issue by sheldonlyr** [shiruken/hackintosh#22]
Thanks for your awesome works! Sorry for my bad english...
I create USB installation and copy your `EFI_install` contents to my EFI volume. When plug into USB 2.0 ports, ports limit reached. When plug into USB 3.0 ports, other issues happened..., Please help!

**Comment by sheldonlyr** [comment]
I have the same motherboard model as yours

**Comment by sheldonlyr** [comment]
When plug into USB 3.0 ports, many com.apple.xpc.launchd messages again, sometimes it says "uncorking source exec upfront" & sometimes it throws "failed lookup" errors

**Comment by shiruken** [comment]
The contents of `EFI_install` are now over 3 years old and may no longer work as expected. I'd recommend referring to the current [OpenCore Install Guide for USB](https://dortania.github.io/OpenCore-Install-Guide/ktext.html#usb) on how to proceed. It appears that they now recommend using the USBToolBox kext and mapping tool.

Alternatively, you can try my [`USBMap.kext`](https://github.com/shiruken/hackintosh/files/6159668/USBMap.kext.zip) I [currently use](https://github.com/shiruken/hackintosh/tree/master?tab=readme-ov-file#map-usb-ports) in my system instead of `USBInjectAll.kext`. Make sure to disable the `XhciPortLimit` quirk too.

**Comment by sheldonlyr** [comment]
> The contents of `EFI_install` are now over 3 years old and may no longer work as expected. I'd recommend referring to the current [OpenCore Install Guide for USB](https://dortania.github.io/OpenCore-Install-Guide/ktext.html#usb) on how to proceed. It appears that they now recommend using the USBToolBox kext and mapping tool.
>
> Alternatively, you can try my [`USBMap.kext`](https://github.com/shiruken/hackintosh/files/6159668/USBMap.kext.zip) I [currently use](https://github.com/shiruken/hackintosh/tree/master?tab=readme-ov-file#map-usb-ports) in my system instead of `USBInjectAll.kext`. Make sure to disable the `XhciPortLimit` quirk too.

Thanks! I will try it while i have free time!
